// flow-typed signature: b6b9b224f90c578c20d6db45def572d5
// flow-typed version: <<STUB>>/mime-types_v2.1.17/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mime-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "mime-types" {
  declare export opaque type MimeType: string
  declare export opaque type ContentType: string
  declare export opaque type Charset: string
  declare export opaque type Extension: string

  declare export function lookup(string): MimeType | false
  declare export function contentType(string): ContentType
  declare export function extension(ContentType): Extension
  declare export function charset(MimeType): Charset
  declare export var types: { [string]: ?ContentType }
  declare export var extensions: { [string]: ?Extension }
}
